# Generated by Django 5.2.5 on 2025-08-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_1', models.PositiveIntegerField()),
                ('horas_2', models.PositiveIntegerField(blank=True, null=True)),
                ('horas_3', models.PositiveIntegerField(blank=True, null=True)),
                ('actividad_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad1', to='eventos.actividad')),
                ('actividad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad2', to='eventos.actividad')),
                ('actividad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad3', to='eventos.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
