# Generated by Django 5.2.5 on 2025-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_actividad_persona_registro_delete_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horas_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horas_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horas_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
